### ISSUE TITLE
Describe Demographics - North Carolina

### ISSUE THREAD

**Issue by dpalencia** [dpalencia/cs541g3#11]

**Comment by dpalencia** [comment]
Which districts are lopsided in terms of demographics

**Comment by MuhammadHayat98** [comment]
I can run mapreduce on this set. Lmk what columns you want in the output data

**Comment by dpalencia** [comment]
I'm dropping a link to a google drive with the CSV's I made over the weekend since the files are too big for github. Good columns to use would be Total Population and the various Race population columns.
