### ISSUE TITLE
PA3 - Writeup

### ISSUE THREAD

**Issue by dpalencia** [dpalencia/cs541g3#18]

**Comment by simrankgill** [comment]
-- Our initial Hypothesize (Are the metrics related to gerrymandering) - Gipson 
-- Cleaning the data - Simran 
-- Analyzing Cleaned data - Erick
-- Statistics :
                   efficiency gap - Simran 
                   partisan bias - Daniel 
                   mean median - Simran 
-- Final finding ( the correlations with metrics) - Daniel
