### ISSUE TITLE
Data Understanding - US Census Demographics

### ISSUE THREAD

**Issue by dpalencia** [dpalencia/cs541g3#4]
Investigate and explore our data to gain an understanding of it. This is also a good opportunity to get familiar with our tools.

### US Census Demographics
https://data.census.gov/cedsci/table?q=All%20Congressional%20Districts%20for%20116th%20Congress%20in%20United%20States&tid=ACSDP5Y2018.DP05&hidePreview=false

1. Load dataset
2. View dataset
3. Identify shape of dataset
4. Attribute types
5. Statistical techniques
6. Data summary based on statistical description
7. Attribute skewness
8. Class distribution
9. Correlations between attributes
10. Data Visualization

**Comment by dpalencia** [comment]
Question: is this the same data as My Congressional District?

**Comment by simrankgill** [comment]
Additional Prompt: Decide which dataset we want to use because these two datasets are very similar.
